name: Mirror to GitLab
on:
  push:
    branches: ["**"]
    tags: ["**"]
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          printf "%s" "${{ secrets.GITLAB_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan gitlab.com >> ~/.ssh/known_hosts

      - name: Add GitLab remote
        run: git remote add gitlab git@gitlab.com:cdlus/fmhy.git

      - name: Push branches and tags (no hidden refs)
        run: |
          # ensure local view is current
          git fetch --prune origin
          # mirror branches and delete removed ones
          git push --prune gitlab "refs/heads/*:refs/heads/*"
          # mirror tags and delete removed ones
          git push --prune gitlab "refs/tags/*:refs/tags/*"
