name: Mirror to GitLab
on:
  push:
    branches: ["**"]
    tags: ["**"]
jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GITLAB_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
      - name: Push mirror
        run: |
          git remote add gitlab git@gitlab.com:cdlus/fmhy.git
          # push all refs and deletions
          git push --mirror gitlab
