name: Sync fork
on:
  schedule:
    - cron: "*/30 * * * *"   # every 30 minutes
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            // auto-detect default branch
            const repoInfo = await github.rest.repos.get({ owner, repo });
            const branch = repoInfo.data.default_branch;
            await github.request('POST /repos/{owner}/{repo}/merge-upstream', {
              owner, repo, branch
            });
